### ISSUE TITLE
[Forge 1.18.2] Crash on startup 

### ISSUE THREAD

**Issue by Zano1999** [legosteenjaap/HorseInBoat#5] opened 2022-05-21 23:10 UTC
Forge version: 40.1.16
Mod version: 1.1.2

Crash log: https://pastebin.com/xvyJhT5T

**Comment by legosteenjaap** [comment] 2022-05-22 09:08
Weird, i can't reproduce this issue. Can you reproduce this without any other mods installed?

**Comment by ProsperCraft** [comment] 2022-05-26 20:01
Same problem with forge .25
horseinboat-forge-1.1.2.jar

https://gist.github.com/ProsperCraft/ffdaf1bdcf5309c906b7df63bfffb2e8

Problem resolved by removing HorseInBoat.

**Comment by legosteenjaap** [comment] 2022-06-04 14:22
Could you send your mod list?

**Closed as completed** 2022-10-21 12:11 UTC
